#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, but 9th ieration display"hi"
n=1
while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n -eq 9 ]
    then
	echo "Hi"
    fi
    ((n++))
done
